'use strict';
const fs = require('fs'), os = require('os'), path = require('path');
const { spawnSync } = require('child_process');
const F = require('ffmpeg-static');
const DS = require('../src/shared');
const { buildExport, chaptersText } = require('../src/exporter');
let fail = 0; const ok = (c, m) => { console.log((c ? '  PASS ' : '  FAIL ') + m); if (!c) fail++; };
console.log('Chapters from markers:');
ok(chaptersText([], 10) === null, 'no markers → no chapters');
const t = chaptersText([{ t: 2, name: 'Intro' }, { t: 5, name: 'a=b;c#d\\e\nline' }, { t: 5.01, name: 'dup' }, { t: 99, name: 'outside' }, { t: NaN, name: 'bad' }], 10);
ok(/title=Intro/.test(t) && /START=0[\s\S]*title=Start/.test(t), 'chapter 0 is added when the first marker is later');
ok(t.split('\n').some((l) => l === 'title=a\\=b\\;c\\#d\\\\e line'), 'special characters are escaped, newlines flattened');
ok(!/dup/.test(t) && !/outside/.test(t) && !/bad/.test(t), 'duplicates, out-of-range and non-numeric markers are dropped');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'chap-'));
const src = tmp + '/a.mp4';
spawnSync(F, ['-y', '-v', 'error', '-f', 'lavfi', '-i', 'testsrc=s=160x90:r=30:d=8', '-f', 'lavfi', '-i', 'sine=d=8', '-shortest', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', src]);
const P = DS.newProject({ width: 160, height: 90, fps: 30, name: 'c' });
P.media = [{ id: 'a', path: src, name: 'a', kind: 'video', duration: 8, hasAudio: true, w: 160, h: 90 }];
P.clips = [DS.newClip({ track: 'V1', media: 'a', start: 0, in: 0, dur: 8 })];
P.markers = [{ t: 1, name: 'One' }, { t: 4, name: '', comments: [{ text: 'Fix the cut' }] }, { t: 7, name: 'Three' }];
const run = (o) => {
  const out = tmp + '/o' + (o.rangeStart || 0) + '.mp4';
  const b = buildExport(P, Object.assign({ outPath: out, scriptPath: tmp + '/s.txt', metaPath: tmp + '/m.txt', newFilterFlag: false, format: 'mp4-h264', quality: 60, chapters: true }, o), {});
  fs.writeFileSync(tmp + '/s.txt', b.script); if (b.metadata) fs.writeFileSync(tmp + '/m.txt', b.metadata);
  const r = spawnSync(F, b.args, { cwd: tmp });
  const pr = spawnSync(F, ['-i', out, '-f', 'ffmetadata', '-'], { maxBuffer: 1 << 24 });
  return { code: r.status, meta: String(pr.stdout), err: String(r.stderr).slice(-300) };
};
let r = run({});
ok(r.code === 0, 'export with chapters succeeds ' + (r.code ? r.err : ''));
const titles = (r.meta.match(/title=.*/g) || []).map((x) => x.slice(6));
ok(titles.join('|') === 'Start|One|Fix the cut|Three', 'file has chapters Start / One / Fix the cut / Three (' + titles.join('|') + ')');
const starts = (r.meta.match(/START=\d+/g) || []).map((x) => +x.slice(6));
ok(starts.join(',') === '0,1000,4000,7000', 'chapter start times in ms (' + starts.join(',') + ')');
r = run({ rangeStart: 3, rangeEnd: 8 });
const st2 = (r.meta.match(/START=\d+/g) || []).map((x) => +x.slice(6));
ok(r.code === 0 && st2.join(',') === '0,1000,4000', 'range export shifts chapters for the range (' + st2.join(',') + ')');
r = run({ chapters: false });
ok(!/\[CHAPTER\]/.test(r.meta), 'no chapters when the option is off');
process.exit(fail ? 1 : 0);
